### ISSUE TITLE
#include <stdexcept>       needed

### ISSUE THREAD

**Issue by MiikaKurkela** [robotrovsky/rpi_i2c_bit_banging#1]
Hello,

I am making a Youtube video that uses your library. It is a good one, thank you.

But to the top of that .cpp file one needs to add
     #include <stdexcept>
that nowadays seems to be needed for the error messages (Raspbian, Geany). 

Would it be a problem for you to add it?

Best regards
Miika Kurkela

**Comment by mwyborski** [comment]
Hi Miika!

No problem. I will add it. I am happy if this helps someone.

Best regards
Marek

**Comment by mwyborski** [comment]
Nice youtube-channel by the way ;-)

**Comment by robotrovsky** [comment]
@MiikaKurkela Have you tried compiling it? I have no rpi to test it right now.
