### ISSUE TITLE
Solve my problem ?

### ISSUE THREAD

**Issue by Pluscrafter** [robotrovsky/rpi_i2c_bit_banging#3]
I have a problem with my IMU(MPU6050) and my DAC(PCA9685). Im using on my IMU the I2cdevlib with DMP and it seems that is critical, when you attach another device on the I2c rail then and when, you comunicate with the DAC the IMU freezes, you connect a 1.8kOhm resistor to 3.3V on the used I2c pins ? 

Thanks for your answer.

**Comment by mwyborski** [comment]
Hi @Pluscrafter,
yes you need pull-ups:

> I2C bus 1 (BCM2 and BCM3) have hard-wired 1k8 pull-ups to 3V3. (see http://pinout.xyz/pinout/pin3_gpio2) When you want to use i2c-bit-banging on other GPIO pins you need external pull-up resistors.
