### ISSUE TITLE
How to implement this libary

### ISSUE THREAD

**Issue by Pluscrafter** [robotrovsky/rpi_i2c_bit_banging#4]
When I want to compile with your lib with g++ -g -Wall -fPIC lwiringPi -o PCA9685.o PCA9685.cpp i2c.o i get following error: .o: file not recognized: File format not recognized.
I had created the i2c.o with: g++ -O -lwiringPi -o i2c.o rpi_i2c_bit_banging.cpp

**Comment by mwyborski** [comment]
if you want to compile but not link use "-c". Althoug the ending is "i2c.o" it is already linked.

> -c
> 
>     Compile or assemble the source files, but do not link. The linking stage simply is not done. The ultimate output is in the form of an object file for each source file.
> 
>     By default, the object file name for a source file is made by replacing the suffix ‘.c’, ‘.i’, ‘.s’, etc., with ‘.o’.
> 
>     Unrecognized input files, not requiring compilation or assembly, are ignored.
> 

https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html#Overall-Options

**Comment by Pluscrafter** [comment]
Thanks the fault was, that I had messed up with the Pin numbers of wiringPi and Pigpio.
