### ISSUE TITLE
Change i2c speed

### ISSUE THREAD

**Issue by benjydel** [robotrovsky/rpi_i2c_bit_banging#6]
Hello, as I use a level shifter to make it work with a 5v i2c bus, I am limited with the i2c speed.
I tried to change the parameter "delayTicks_" but with the rpi4, the i2c_delay() function is still too fast and so it doesn't work.
I understand why you used a loop because usleep is limited to 80us but I suggest to replace it with `delayMicroseconds()` as wiringpi is used.
The new i2c_delay() function should be :
```
void i2cBitBangingBus::i2c_delay()
{
   // unsigned int index;
    //for (index = 0; index < delayTicks; index++)
    //    ;
    delayMicroseconds(delayTicks);
}
```
With delayTicks_ set to 5us when creating a bus, I manage to change the speed of 1Mhz to 100Khz ;)

**Comment by mwyborski** [comment]
Hi Benjamin,
The function was copied from wikipedia ;-) Also i might have been focused on maximum speed and my device just worked.

I think the best would be to configure the speed during bus-initialization and then set the sleep time like you did. If you like, make a pull request with your solution?

Glad that it works for you!
